global:
  marketplace-ami: false
  owner: jorge@aviatrix.com
  regions:
    - us-east-1
  reporting: true
tests:
  avx-awsmp-byol:
    parameter_input: avx-awsmp-byol-params.json
    template_file: avx-awsmp-byol.template
